obj-$(CONFIG_SILEAD_FP)				+= silead/
obj-$(CONFIG_SILEAD_FP_PLATFORM)		+= silead/
obj-$(CONFIG_FINGERPRINT_SUNWAVE)		+= sunwave/
obj-$(CONFIG_NUBIA_SENSORS_FP)			+= gf5288_left/
obj-$(CONFIG_NUBIA_SENSORS_FP)			+= gf5288_right/

