### virtual sensor
obj-$(CONFIG_NUBIA_DOUBLE_SENSORS) += virtual_light.o virtual_proximity.o sensor_common.o
### Front ALS
obj-$(CONFIG_NUBIA_SENSORS_FRONT_RGB_BH1745) += bh1745/
### Front PS
obj-$(CONFIG_NUBIA_SENSORS_FRONT_PS_STK3332) += stk3332/
### Back ALS & PS
obj-$(CONFIG_NUBIA_SENSORS_BACK_TMD2725)     += tmd2725/
