obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX) += synaptics_dsx/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX8) += goodix_touch/
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_DSX) += nubia_synaptics_dsx/
obj-$(CONFIG_TOUCHSCREEN_NUBIA_BACK_GOODIX) += goodix_gtx8_back/
obj-$(CONFIG_TOUCHSCREEN_NUBIA_FRONT_GOODIX) += goodix_gtx8_front/
